version: '3.8'

services:
  fake-news-detection:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake-news-detection
    ports:
      - "8000:8000"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8000 --no-browser --allow-root
