version: '3.8'

services:
  fake-real-news-detection:
    image: vindictive/fake-real-news-detection:latest
    container_name: fake-real-news-detection
    ports:
      - "8000:8000"
    environment:
      - JUPYTER_ENABLE_LAB=yes
