name: fake-news-detection
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - conda-lock
  - altair
  - scipy
  - pip
  - pip:
    - wordcloud
    - matplotlib
