name: fake-news-detection
channels:
  - conda-forge
dependencies:
  - scikit-learn
  - python=3.12
  - jupyter
  - conda-lock
  - pandas
  - altair
  - vegafusion[version='>=2.0.3']
  - vl-convert-python[version='>=1.8.0']
  - vegafusion-python-embed
  - pyarrow
