name: fake-news-detection
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - conda-lock
  - scipy
  - wordcloud
  - matplotlib
  - altair
  - vegafusion
  - vl-convert-python
  - pyarrow