name: fake-news-detection
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - conda-lock
  - scipy
  - altair
  - vegafusion
  - vl-convert-python
  - pyarrow
  - pip
  - pip:
    - wordcloud
    - matplotlib
    